# Generated by Django 4.0.3 on 2024-02-26 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_usertagcount_userprofile_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
